pipeline {
    agent any   {
       stage('Build') { 
        mvn build
    }
    stage('Test') { 
       echo "test is running" 
    }
    stage('Deploy') { 
        mvn package
    }
    }
}
